# DataSource Config
server:
  port: 8089

spring:
  redis:
    host: 43.136.178.202
    port: 6379
    # password: 93449344
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.136.178.202:3306/hospital_db?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql9344!
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: HikariPool-1
#  web:
#    resources:
#      # 将E盘的图片目录映射为http://localhost:8081/images/访问, classpath:/static/：保留了默认的静态资源目录(优先级：从左到右)
#      static-locations: file:/E:/Download/project/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,
#      add-mappings: true
# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross:
      origin: '*'

# Redis客户端Redisson配置信息
redis:
  sdk:
    config:
      host: 43.136.178.202
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
      # password: 93449344

mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # map-underscore-to-camel-case: false



shiro-redis:
  enabled: true
  redis-manager:
    host: 43.136.178.202:6379
 #   password: 93449344       # 用redis-manager的时候也要给到redis的password

highmyopia:
  jwt:
    # 加密密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长， 7天， 单位秒
    expire: 604800
    header: Authorization

hospital:
  AHisHost: http://acloud.aierchina.com:8010/external-api
  APacsHost: http://110.185.171.30:8083  # http://10.0.225.6:8083
  filePath: E:\Download\project
  # 这个路径是在原来filePath后面+pdfImg,这里加了个后\
  pdf2ImgPath: \pdfImg
  # 本地图片映射路径
  localImage: /images
  flask_path: http://localhost:4091

  hospId: 1824
  appKey: Cdm_1824
  appSecret: h2md.scxm

  vision-hospId: 9999
  vision-appKey: aviseq_9999
  vision-appSecret: lsj.z4HzPyAA



# 接口文档配置
# 访问 http://localhost:8081/doc.html
knife4j:
  enable-token: true
  token-header-name: Authorization
  # 这里的token是jwt令牌
  token-value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxNCIsInN0YXR1cyI6MSwiaWF0IjoxNzM1NjE2NDk2LCJleHAiOjE3MzYyMjEyOTZ9.XJf1fsdCBRT6mhN4FEHjV4m8d7emkQO5HTOMduDVh4hbVwoitMqWnuuD9TYOeHdkWkPCprKleNSIBPUcx5T3Xw
#  basic: #开启密码验证
#    enable: true
#    username: root
#    password: 123456


logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework.jdbc.core.JdbcTemplate: OFF
    org.springframework.jdbc.core.StatementCreatorUtils: OFF