# 全局设置
global:
  device: "cuda"  # 使用 GPU
  log_level: "info"
  output_dir: "./outputs"
  seed: 42

# 模型配置
models:
  diabetic_retinopathy:
    model_path: "./models/dr_model.onnx"
    input_shape: [1, 3, 224, 224]  # ONNX模型的输入张量形状，假设为单通道、3通道224x224图像
    output_layer: "softmax"  # 输出层的类型，指定为softmax
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]

  myopia_detection:
    model_path: "./models/myopia_model.onnx"
    input_shape: [1, 3, 224, 224]
    output_layer: "softmax"
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]

# 推理配置
inference:
  batch_size: 32
  device: "cuda"  # 或 "cpu"
  num_workers: 4  # 数据加载的线程数

# 输入输出设置
data:
  input_data_path: "./data/input_images"
  output_data_path: "./outputs/predictions"
  image_size: [224, 224]  # 统一输入大小
